version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eventsdb
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /data/mysql